<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subjects = [
            [
                'name' => 'Coding 5-8',
                'code' => 'CODE-0001',
                'price' => '100',
                'duration' => '10',
                'short_description' => 'Complete Coding Course.',
                'rating' => 4.4,
                'total_enrolled' => 112,
                'from_age' => 5,
                'to_age' => 8,
                'image' => 'uploads/subjects/coding.webp',
            ],
            [
                'name' => 'Coding 9-15',
                'code' => 'CODE-0002',
                'price' => '100',
                'duration' => '10',
                'short_description' => 'Complete Coding Course.',
                'rating' => 4.4,
                'total_enrolled' => 112,
                'from_age' => 9,
                'to_age' => 15,
                'image' => 'uploads/subjects/coding.webp',
            ],
            [
                'name' => 'Artifitial Intelligence (AI) 5-8',
                'code' => 'AI-0003',
                'price' => '180',
                'duration' => '15',
                'short_description' => 'Complete Artifitial Intelligence (AI) Course.',
                'rating' => 4.2,
                'total_enrolled' => 88,
                'from_age' => 5,
                'to_age' => 8,
                'image' => 'uploads/subjects/ai.jpg',
            ],
            [
                'name' => 'Artifitial Intelligence (AI) 9-15',
                'code' => 'AI-0004',
                'price' => '180',
                'duration' => '15',
                'short_description' => 'Complete Artifitial Intelligence (AI) Course.',
                'rating' => 4.2,
                'total_enrolled' => 88,
                'from_age' => 9,
                'to_age' => 15,
                'image' => 'uploads/subjects/ai.jpg',
            ],
            [
                'name' => 'Mathematics 5-8',
                'code' => 'MATH-0005',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Mathematics Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 5,
                'to_age' => 8,
                'image' => 'uploads/subjects/math.jpg',
            ],
            [
                'name' => 'Mathematics 9-15',
                'code' => 'MATH-0006',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Mathematics Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 9,
                'to_age' => 15,
                'image' => 'uploads/subjects/math.jpg',
            ],
            [
                'name' => 'Reading 5-8',
                'code' => 'READ-0007',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Reading Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 5,
                'to_age' => 8,
                'image' => 'uploads/subjects/reading.jpg',
            ],
            [
                'name' => 'Reading 9-15',
                'code' => 'READ-0008',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Reading Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 9,
                'to_age' => 15,
                'image' => 'uploads/subjects/reading.jpg',
            ],
            [
                'name' => 'Robotics 5-8',
                'code' => 'ROBOT-0009',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Robotics Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 5,
                'to_age' => 8,
                'is_coming' => '1',
                'image' => 'uploads/subjects/robotics.jpg',
            ],
            [
                'name' => 'Robotics 9-15',
                'code' => 'ROBOT-0010',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Robotics Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 9,
                'to_age' => 15,
                'is_coming' => '1',
                'image' => 'uploads/subjects/robotics.jpg',
            ],
            [
                'name' => 'Machine Learning 5-8',
                'code' => 'ML-0011',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Machine Learning Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 5,
                'to_age' => 8,
                'is_coming' => '1',
                'image' => 'uploads/subjects/machine-learning.jpg',
            ],
            [
                'name' => 'Machine Learning 9-15',
                'code' => 'ML-0012',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Machine Learning Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 9,
                'to_age' => 15,
                'is_coming' => '1',
                'image' => 'uploads/subjects/machine-learning.jpg',
            ],
            [
                'name' => 'Abacus 5-8',
                'code' => 'AB-0013',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Abacus Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 5,
                'to_age' => 8,
                'is_coming' => '1',
                'image' => 'uploads/subjects/abacus.jpg',
            ],
            [
                'name' => 'Abacus 9-15',
                'code' => 'AB-0014',
                'price' => '220',
                'duration' => '18',
                'short_description' => 'Complete Abacus Course.',
                'rating' => 4.6,
                'total_enrolled' => 107,
                'from_age' => 9,
                'to_age' => 15,
                'is_coming' => '1',
                'image' => 'uploads/subjects/abacus.jpg',
            ],
        ];

        foreach ($subjects as $subject) {
            Subject::create($subject);
        }
    }
}
